# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 00:09
from __future__ import unicode_literals

import apps.miniregister.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, validators=[apps.miniregister.models.validateLengthAtLeastThree])),
                ('last_name', models.CharField(max_length=45, validators=[apps.miniregister.models.validateLengthAtLeastThree])),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator])),
                ('password', models.CharField(max_length=255, validators=[apps.miniregister.models.validateLengthAtLeastEight])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
