# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:16
from __future__ import unicode_literals

import apps.users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, validators=[apps.users.models.validateIsNotEmpty])),
                ('alias', models.CharField(max_length=45, validators=[apps.users.models.validateIsNotEmpty])),
                ('email', models.CharField(max_length=45, validators=[django.core.validators.EmailValidator])),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
