var numberOne = -1;
console.log("The First Number:", numberOne);
var numberTwo = 0.2;
console.log("The Second Number:", numberTwo);
var numberThree = 3000000;
console.log("The Third Number:", numberThree);
var numberFour = 2 * 2;
console.log("The Fourth Number:", numberFour);
var stringOne = 'one';
console.log("The First String:", stringOne);
var stringTwo = 'two';
console.log("The Second String:", stringTwo);
var stringThree = 'three';
console.log("The Third String:", stringThree);
var boolOne = true;
console.log("The First Bool:", boolOne);
var boolTwo = false;
console.log("The Second Bool:", boolTwo);
var none = undefined;
console.log("The Undefined:", none);
